name: flux_firebase
description: A Firebase package for FluxStore apps
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fstore:
    path: ../../

  inspireui: 2.2.3
  flux_ui: 0.0.1

  flux_interface:
    path: ../flux_interface

  flux_localization:
    path: ../flux_localization

  # FIREBASE PACKAGES
  firebase_core: 3.8.0
  firebase_analytics: 11.3.5
  firebase_auth: 5.3.3
  firebase_remote_config: 5.1.5
  firebase_dynamic_links: 6.0.10
  cloud_firestore: 5.5.0
  firebase_remote_config_web: 1.7.4

  # Additional Firebase packages. To prevent unexpected upgrade.
  firebase_core_platform_interface: 5.3.0
  firebase_analytics_platform_interface: 4.2.7
  firebase_auth_platform_interface: 7.4.9
  firebase_remote_config_platform_interface: 1.4.46
  firebase_dynamic_links_platform_interface: 0.2.6+46
  cloud_firestore_platform_interface: 6.5.0
  firebase_messaging_platform_interface: 4.5.48

  # PUSH NOTIFICATION
  firebase_messaging: 15.1.5

  # OTHERS
  intl: any
  timeago: 3.7.0
  flutter_local_notifications: 18.0.0
  share_plus: 10.1.1
  provider: 6.1.2
  collection: any
  easy_debounce: 2.0.3
  jumping_dot: 0.0.7
  flutter_linkify: 6.0.0

flutter:
  uses-material-design: true
